generator/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'account'
urlpatterns = [
    # Logging
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # Password change
    path('password_change/', views.CustomChangePasswordView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # Password reset
    path('password_reset/', views.CustomResetPasswordView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomResetPasswordConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # Registration
    path('register/', views.register, name='register'),

    # Main page
    path('dashboard/', views.dashboard, name='dashboard'),
    path('', views.main, name='main'),

]

generator/generator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('dashboard/', include('questions.urls', namespace='questions')),
    path('dashboard/', include('quiz.urls', namespace='quiz')),
    path('', include('account.urls', namespace='account')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

generator/questions/urls.py
from django.urls import path
from . import views

app_name = 'questions'
urlpatterns = [
    # Question and answers
    path('subject/<int:subject_id>/<slug:subject_slug>/<int:question_id>/', views.question, name='question'),
    path('subject/<int:subject_id>/<slug:subject_slug>/<int:question_id>/edit/',
         views.edit_question, name='question-edit'),
    path('subject/<int:subject_id>/<slug:subject_slug>/<int:question_id>/add-answer/',
         views.add_answer, name='question-add-answer'),
    path('subject/<int:subject_id>/<slug:subject_slug>/<int:question_id>/<int:answer_id>/edit-answer/',
         views.edit_answer, name='question-edit-answer'),
    path('subject/<int:subject_id>/<slug:subject_slug>/add-question/', views.create_question, name='question-create'),

    # Subject
    path('subject/<int:subject_id>/<slug:subject_slug>/edit/', views.edit_subject, name='subject-edit'),
    path('subject/<int:subject_id>/<slug:subject_slug>/people/add/', views.add_owner, name='subject-add-owner'),
    path('subject/<int:subject_id>/<slug:subject_slug>/people/', views.people, name='subject-people'),
    # List of questions in subject
    path('subject/<int:subject_id>/<slug:subject_slug>/tag/<slug:tag_slug>/', views.subject, name='subject-by-tag'),
    path('subject/<int:subject_id>/<slug:subject_slug>/', views.subject, name='subject'),
    path('subject/create/', views.create_subject, name='subject-create'),
]

generator/quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'
urlpatterns = [
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/create/', views.create_quiz, name='create-quiz'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/<int:quiz_id>/<slug:quiz_slug>/edit/',
         views.edit_quiz, name='edit-quiz'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/<int:quiz_id>/<slug:quiz_slug>/tag/<slug:tag_slug>',
         views.quiz, name='quiz-questions-by-tag'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/<int:quiz_id>/<slug:quiz_slug>/add-question/tag/<slug:tag_slug>/',
         views.add_question_to_quiz, name='add-question-to-quiz-by-tag'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/<int:quiz_id>/<slug:quiz_slug>/add-question/',
         views.add_question_to_quiz, name='add-question-to-quiz'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/<int:quiz_id>/<slug:quiz_slug>/',
         views.quiz, name='quiz'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/<int:quiz_id>/<slug:quiz_slug>/pdf/',
         views.quiz_pdf, name='quiz-pdf'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/tag/<slug:tag_slug>/', views.quizzes, name='quiz-by-tag'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/', views.quizzes, name='quizzes'),
]

generator/questions/forms.py
from django import forms
from taggit.forms import TagWidget

from .models import Subject, Question, Answer


class SubjectCreationForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'

    class Meta:
        model = Subject
        fields = ('name', 'description')


class QuestionCreationForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('question', 'tags')
        widgets = {
            'tags': TagWidget()
        }


class AnswerCreationForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            if visible.name == 'is_right':
                visible.field.widget.attrs['class'] = 'form-check-input'

    class Meta:
        model = Answer
        fields = ('answer', 'is_right')


class SearchForm(forms.Form):
    query = forms.CharField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'


class SearchTagForm(forms.Form):
    tag_query = forms.CharField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'

generator/questions/views.py
import re

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.postgres.search import TrigramSimilarity, SearchVector, SearchQuery, SearchRank
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views.decorators.http import require_http_methods
from taggit.models import Tag

from .forms import SubjectCreationForm, QuestionCreationForm, AnswerCreationForm, SearchForm, SearchTagForm
from .models import Subject, Question, Answer
from .utils import (is_author_of_subject, is_owner_of_subject, is_author_of_question)


@login_required
@require_http_methods(['GET', 'POST'])
def create_subject(request):
    if request.method == 'POST':
        subject_form = SubjectCreationForm(data=request.POST)
        if subject_form.is_valid():
            new_subject = subject_form.save(commit=False)
            new_subject.author = request.user
            new_subject.save()  # First subject needs to get the id before ownership can be added
            new_subject.ownership.add(request.user)
            new_subject.save()
            return redirect('account:dashboard')
    else:
        subject_form = SubjectCreationForm()
    return render(request, 'questions/subject_form.html', {'subject_form': subject_form, 'section': 'create_subject'})


@login_required
@require_http_methods(['GET', 'POST'])
def edit_subject(request, subject_id, subject_slug):
    # Check if user is an author of a subject - only author can edit a subject (name, description)
    if not is_author_of_subject(request.user, subject_id):
        return redirect('account:dashboard')  # Just redirect - do not inform about illegal action

    if request.method == 'POST':
        subject_form = SubjectCreationForm(data=request.POST)
        if subject_form.is_valid():
            subject = get_object_or_404(Subject, id=subject_id)
            subject.name = subject_form.cleaned_data['name']
            subject.description = subject_form.cleaned_data['description']
            subject.save()
            return redirect('account:dashboard')
    else:
        subject = get_object_or_404(Subject, id=subject_id)
        subject_form = SubjectCreationForm(instance=subject)
        return render(request, 'questions/subject_form.html', {'subject_form': subject_form, 'section': 'edit_subject',
                                                               'subject': subject})


@login_required
@require_http_methods(['GET', 'POST'])
def subject(request, subject_id, subject_slug, tag_slug=None):
    # Question deletion
    if request.method == 'POST':
        try:
            # Check if user is an author of a subject or an author of a question
            question_id = int(request.POST.get('delete'))
            if not is_author_of_question(request.user, question_id) and \
                    not is_author_of_subject(request.user, subject_id):
                raise Exception

            Question.objects.filter(id=question_id).delete()
        except Exception:
            pass

    # GET (and POST)
    # Check if user is an owner of a subject - only owners can access the subject's questions
    if not is_owner_of_subject(request.user, subject_id):
        return redirect('account:dashboard')

    subject = get_object_or_404(Subject, id=subject_id)
    questions = subject.questions.all()

    # Query search - questions and answers
    search_form = SearchForm()
    q = None
    if 'query' in request.GET:
        search_form = SearchForm(request.GET)
        if search_form.is_valid():
            q = search_form.cleaned_data['query']

            # Rank search
            vector = SearchVector('question', 'answers__answer')
            query = SearchQuery(q)
            questions = questions.annotate(rank=SearchRank(vector, query)).filter(rank__gte=0.001).order_by('-rank') \
                .distinct()

    # Query search - tags
    tag_search_form = SearchTagForm()
    tag_query = None
    if 'tag_query' in request.GET:
        tag_search_form = SearchTagForm(request.GET)
        if tag_search_form.is_valid():
            tag_query = tag_search_form.cleaned_data['tag_query']
            # Trigram search
            questions = questions.annotate(
                similarity=TrigramSimilarity('tags__name', tag_query)
            ).filter(similarity__gt=0.1).order_by('id', '-similarity').distinct('id')

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        questions = questions.filter(tags__in=[tag])

    paginator = Paginator(questions, 10)
    page = request.GET.get('page')
    try:
        questions_page = paginator.page(page)
    except PageNotAnInteger:
        # If page value is not int - get first page
        questions_page = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
        # If page value is bigger than the value of last page - get last page
        questions_page = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request, 'questions/subject_questions_ajax.html', {'subject': subject,
                                                                         'questions': questions_page,
                                                                         'tag': tag, 'query': q,
                                                                         'search_form': search_form,
                                                                         'tag_query': tag_query,
                                                                         'tag_search_form': tag_search_form})

    return render(request, 'questions/subject_questions.html', {'subject': subject, 'questions': questions_page,
                                                                'tag': tag, 'query': q,
                                                                'search_form': search_form,
                                                                'tag_query': tag_query,
                                                                'tag_search_form': tag_search_form})


@login_required
@require_http_methods(['GET', 'POST'])
def create_question(request, subject_id, subject_slug):
    if request.method == 'POST':
        question_form = QuestionCreationForm(data=request.POST)
        if question_form.is_valid():
            new_question = question_form.save(commit=False)
            subject = get_object_or_404(Subject, id=subject_id)
            new_question.subject = subject
            new_question.author = request.user
            new_question.save()
            question_form.save_m2m()
            return redirect(new_question.get_absolute_url())
    else:
        question_form = QuestionCreationForm()
    return render(request, 'questions/question_create.html', {'question_form': question_form, 'subject_id': subject_id,
                                                              'subject_slug': subject_slug})


@login_required
@require_http_methods(['GET', 'POST'])
def question(request, subject_id, subject_slug, question_id):
    # Check if a user is an author of subject or an author of a question
    if is_author_of_subject(request.user, subject_id) or is_author_of_question(request.user, question_id):
        # Question/answer deletion or answer ordinal number change
        if request.method == 'POST':

            if 'delete-question' in request.POST:
                try:
                    question_id = int(request.POST.get('delete-question'))
                    Question.objects.filter(id=question_id).delete()
                except Exception:
                    pass
                return redirect(Subject.objects.get(id=subject_id).get_absolute_url())

            elif 'delete-answer' in request.POST:
                try:
                    answer_id = int(request.POST.get('delete-answer'))
                    Answer.objects.filter(id=answer_id).delete()
                except Exception:
                    pass
                return redirect(Question.objects.get(id=question_id).get_absolute_url())

            elif 'up' in request.POST:
                answer_to_go_up = get_object_or_404(Answer, id=int(request.POST.get('up')))
                question = get_object_or_404(Question, id=question_id)
                answer_to_go_down = question.answers.filter(question=question, order__lt=answer_to_go_up.order) \
                    .order_by('-order').first()
                with transaction.atomic():
                    temp_order = answer_to_go_up.order
                    answer_to_go_up.order = answer_to_go_down.order
                    answer_to_go_down.order = temp_order
                    answer_to_go_up.save()
                    answer_to_go_down.save()
                return redirect(Question.objects.get(id=question_id).get_absolute_url())

            elif 'down' in request.POST:
                answer_to_go_down = get_object_or_404(Answer, id=int(request.POST.get('down')))
                question = get_object_or_404(Question, id=question_id)
                answer_to_go_up = question.answers.filter(question=question, order__gt=answer_to_go_down.order) \
                    .order_by('order').first()
                with transaction.atomic():
                    temp_order = answer_to_go_down.order
                    answer_to_go_down.order = answer_to_go_up.order
                    answer_to_go_up.order = temp_order
                    answer_to_go_down.save()
                    answer_to_go_up.save()
                return redirect(Question.objects.get(id=question_id).get_absolute_url())

        else:  # GET
            question = get_object_or_404(Question, id=question_id)
            answers = question.answers.all().order_by('order')

generator/questions/templates/questions/people.html
{% extends 'base.html' %}

{% block title %}
    {{ subject.name }} - people
{% endblock %}

{% block content %}
    <section class="min-vh-100 gradient-custom container-fluid pb-5">
        <div class="d-flex justify-content-between position-relative top-0 start-0">
            <a class="btn btn-primary mt-2 ms-4" href="{% url 'questions:subject' subject.id subject.slug %}">
                Return to Subject
            </a>
            <a class="btn btn-success mt-2 ms-4" href="{% url 'questions:subject-add-owner' subject.id subject.slug %}">
                Add new Owner
            </a>
        </div>

        <h1 class="text-light text-center pt-4">
            <a class="text-decoration-none text-light"
               href="{% url 'questions:subject-people' subject.id subject.slug %}">
                {{ subject.name }} <br>
                People
            </a>
        </h1>

        <h3 class="h3 text-light text-center pt-4">
            Author of Subject
        </h3>

        <div class="container mx-auto px-auto">
            <div class="card bg-dark text-light">
                <div class="card-body">
                    <h5 class="card-title">{{ subject.author.username }} <span class="text-danger">(you)</span></h5>
                </div>
            </div>
        </div>

        <h3 class="h3 text-light text-center pt-4">
            Owners of Subject
        </h3>

        <div class="container mx-auto px-auto">
            {% for owner in owners %}
                <div class="card bg-dark text-light mt-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ owner.username }}</h5>
                        <button type="button" data-mdb-toggle="modal"
                                data-mdb-target="#delete{{ owner.id }}"
                                class="btn btn-danger mt-2">
                            Remove from Subject
                        </button>
                    </div>
                </div>

                {# Delete dialog #}
                <div class="modal" tabindex="-1" role="dialog" id="delete{{ owner.id }}">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Remove Owner</h5>
                                <button type="button" class="btn-close" data-mdb-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                <p>Are you sure you want to remove {{ owner.username }} from {{ subject.name }}?</p>
                            </div>
                            <div class="modal-footer">
                                <form method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="delete" value="{{ owner.id }}">
                                    <button type="submit" class="btn btn-danger">Yes, remove</button>
                                </form>
                                <button type="button" class="btn btn-success" data-mdb-dismiss="modal">
                                    No, cancel
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>

        <div class="position-fixed bottom-0 end-0 mb-3 me-3" style="z-index: 9999">
            <button type="button" class="btn btn-warning btn-floating btn-lg" id="scrollBtn" style="display: none">
                <i class="fas fa-arrow-up"></i>
            </button>
        </div>

    </section>


    <script>
        let scrollBtn = document.getElementById("scrollBtn");

        // When the user scrolls down 20px from the top of the document, show the button
        window.onscroll = function () {
            scrollFunction()
        };

        function scrollFunction() {
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                scrollBtn.style.display = "block";
            } else {
                scrollBtn.style.display = "none";
            }
        }

        scrollBtn.addEventListener("click", topFunction);

        // When the user clicks on the button, scroll to the top of the document
        function topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
        }
    </script>

{% endblock %}

generator/questions/templates/questions/question.html
{% extends 'base.html' %}

{% block title %}
    Question Details
{% endblock %}

{% block content %}
    <section class="min-vh-100 gradient-custom container-fluid">

        <div class="position-relative top-0 start-0">
            <a class="btn btn-primary mt-2 ms-4" href="{% url 'questions:subject' question.subject.id question.subject.slug %}">Return to Questions</a>
        </div>

        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">

                <h3 class="h3 text-light text-center">Question</h3>

                <div class="container">
                    <div class="col-12 bg-white rounded py-1 my-2">

                        <nav class="navbar navbar-light bg-light mb-4">
                            <div class="container-fluid">
                                <a class="btn btn-success"
                                   href="{% url 'questions:question-edit' question.subject.id question.subject.slug question.id %}">
                                    Edit
                                </a>
                                <div class="d-flex justify-content-center">
                                    {% for tag in question.tags.all %}
                                        <a
                                                href="{% url 'questions:subject-by-tag' question.subject.id question.subject.slug tag.slug %}"
                                                class="badge badge-primary mx-1">{{ tag.name }}
                                        </a>
                                    {% endfor %}
                                </div>
                                <button type="button" data-mdb-toggle="modal"
                                        data-mdb-target="#delete{{ question.id }}"
                                        class="btn btn-danger my-2 mx-3">
                                    Delete
                                </button>
                            </div>
                        </nav>

                        <div class="mx-3">
                            {{ question.question|safe }}
                        </div>

                    </div>
                    {# Delete dialog #}
                    <div class="modal" tabindex="-1" role="dialog" id="delete{{ question.id }}">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Delete Question</h5>
                                    <button type="button" class="btn-close" data-mdb-dismiss="modal"></button>
                                </div>
                                <div class="modal-body">
                                    <p>Are you sure you want to delete the question?</p>
                                </div>
                                <div class="modal-footer">
                                    <form method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="delete-question" value="{{ question.id }}">
                                        <button type="submit" class="btn btn-danger">Yes, delete</button>
                                    </form>
                                    <button type="button" class="btn btn-success" data-mdb-dismiss="modal">
                                        No, cancel
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <h3 class="h3 text-light text-center">Answers</h3>

                {% for answer in answers %}

                    <div class="container">
                        <div class="col-12 bg-white rounded py-1 my-2"
                                {% if answer.is_right %}
                             style="border: 10px green solid; border-radius: 25px"
                                {% else %}
                             style="border: 10px red solid; border-radius: 25px"
                                {% endif %}
                        >

                            <nav class="navbar navbar-light bg-light mb-4">
                                <div class="container-fluid">
                                    <a class="btn btn-success my-2 mx-3"
                                       href="{% url 'questions:question-edit-answer' question.subject.id question.subject.slug question.id answer.id %}">
                                        Edit
                                    </a>

                                    <div>
                                        {% if forloop.first and forloop.first != forloop.last %}
                                            <form method="post">
                                                {% csrf_token %}
                                                <input type="hidden" name="down" value="{{ answer.id }}">
                                                <button type="submit" class="btn btn-primary btn-floating btn-md">
                                                    <i class="fas fa-arrow-down"></i>
                                                </button>
                                            </form>
                                        {% elif forloop.last and forloop.first != forloop.last %}
                                            <form method="post">
                                                {% csrf_token %}
                                                <input type="hidden" name="up" value="{{ answer.id }}">
                                                <button type="submit" class="btn btn-primary btn-floating btn-md">
                                                    <i class="fas fa-arrow-up"></i>
                                                </button>
                                            </form>
                                        {% elif not forloop.first and not forloop.last %}
                                            <form method="post" class="me-1" style="float: left">
                                                {% csrf_token %}
                                                <input type="hidden" name="down" value="{{ answer.id }}">
                                                <button type="submit" class="btn btn-primary btn-floating btn-md">
                                                    <i class="fas fa-arrow-down"></i>
                                                </button>
                                            </form>
                                            <form method="post" class="ms-1" style="float:left;">
                                                {% csrf_token %}
                                                <input type="hidden" name="up" value="{{ answer.id }}">
                                                <button type="submit" class="btn btn-primary btn-floating btn-md">
                                                    <i class="fas fa-arrow-up"></i>
                                                </button>
                                            </form>
                                        {% endif %}
                                    </div>

                                    <button type="button" data-mdb-toggle="modal"
                                            data-mdb-target="#delete{{ answer.id }}"
                                            class="btn btn-danger my-2 mx-3">
                                        Delete
                                    </button>
                                </div>
                            </nav>

                            <div class="col-12 bg-white rounded p-2 my-2">
                                {{ answer.answer|safe }}
                            </div>

                        </div>
                        {# Delete dialog #}
                        <div class="modal" tabindex="-1" role="dialog" id="delete{{ answer.id }}">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">Delete Question</h5>
                                        <button type="button" class="btn-close" data-mdb-dismiss="modal"></button>
                                    </div>
                                    <div class="modal-body">
                                        <p>Are you sure you want to delete the answer?</p>
                                    </div>
                                    <div class="modal-footer">
                                        <form method="post">
                                            {% csrf_token %}
                                            <input type="hidden" name="delete-answer" value="{{ answer.id }}">
                                            <button type="submit" class="btn btn-danger">Yes, delete</button>
                                        </form>
                                        <button type="button" class="btn btn-success" data-mdb-dismiss="modal">
                                            No, cancel
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                {% endfor %}


                <div class="card col-md-12 bg-dark text-light my-3 py-2">
                    <div class="card-body">
                        <h5 class="card-title text-center">Add Answer</h5>
                        <p class="card-text text-center">
                            <a href="{% url 'questions:question-add-answer' question.subject.id question.subject.slug question.id %}">
                                <i class="fas fa-plus fa-5x mt-4"></i>
                            </a>
                        </p>
                    </div>
                </div>

            </div>
        </div>
    </section>
{% endblock %}

generator/questions/templates/questions/subject.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>