generator/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'account'
urlpatterns = [
    # Logging
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # Password change
    path('password_change/', views.CustomChangePasswordView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # Password reset
    path('password_reset/', views.CustomResetPasswordView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomResetPasswordConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # Registration
    path('register/', views.register, name='register'),

    # Main page
    path('dashboard/', views.dashboard, name='dashboard'),
    path('', views.main, name='main'),

]

generator/generator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('dashboard/', include('questions.urls', namespace='questions')),
    path('dashboard/', include('quiz.urls', namespace='quiz')),
    path('', include('account.urls', namespace='account')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

generator/quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'
urlpatterns = [
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/create/', views.create_quiz, name='create-quiz'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/<int:quiz_id>/<slug:quiz_slug>/edit/',
         views.edit_quiz, name='edit-quiz'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/<int:quiz_id>/<slug:quiz_slug>/tag/<slug:tag_slug>',
         views.quiz, name='quiz-questions-by-tag'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/<int:quiz_id>/<slug:quiz_slug>/add-question/tag/<slug:tag_slug>/',
         views.add_question_to_quiz, name='add-question-to-quiz-by-tag'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/<int:quiz_id>/<slug:quiz_slug>/add-question/',
         views.add_question_to_quiz, name='add-question-to-quiz'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/<int:quiz_id>/<slug:quiz_slug>/',
         views.quiz, name='quiz'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/<int:quiz_id>/<slug:quiz_slug>/pdf/',
         views.quiz_pdf, name='quiz-pdf'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/tag/<slug:tag_slug>/', views.quizzes, name='quiz-by-tag'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/', views.quizzes, name='quizzes'),
]

generator/account/models.py
from django.db import models

generator/account/forms.py
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox
from django.contrib.auth.forms import (AuthenticationForm,
                                       PasswordChangeForm,
                                       PasswordResetForm,
                                       SetPasswordForm,
                                       UserCreationForm)
from django.contrib.auth.models import User


class CustomLoginForm(AuthenticationForm):
    """
    Adds some classes to default AuthenticationForm fields.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'


class CustomChangePasswordForm(PasswordChangeForm):
    """
    Adds some classes to default PasswordChangeForm fields.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'


class CustomResetPasswordForm(PasswordResetForm):
    """
    Adds some classes to default PasswordResetForm fields.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'


class CustomResetPasswordConfirmForm(SetPasswordForm):
    """
    Adds some classes to default SetPasswordForm fields.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'


class CustomUserCreationForm(UserCreationForm):
    """
    Adds some classes to default UserCreationForm fields and decides which specific User model fields to show in a form.
    """
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox(attrs={'data-theme': 'dark'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')

generator/account/views/views_logged.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods

from account.forms import CustomChangePasswordForm
from questions.models import Subject
from questions.utils import is_author_of_subject


@login_required
@require_http_methods(['GET', 'POST'])
def dashboard(request):
    # Subject deletion
    if request.method == 'POST':
        try:
            # Check if user is an author of a subject - only author can delete subject
            subject_id = int(request.POST.get('delete'))
            if not is_author_of_subject(request.user, subject_id):
                raise Exception

            Subject.objects.filter(id=subject_id).delete()
        except Exception:
            return redirect('account:dashboard')

    subjects = Subject.objects.filter(ownership=request.user)
    authorial_subjects = Subject.objects.filter(author=request.user)
    return render(request, 'account/dashboard.html',
                  {'section': 'dashboard', 'subjects': subjects, 'authorial_subjects': authorial_subjects})


class CustomChangePasswordView(LoginRequiredMixin, PasswordChangeView):
    form_class = CustomChangePasswordForm
    success_url = '/password_change/done/'

generator/account/views/views_logging.py
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetConfirmView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from account.forms import CustomLoginForm
from account.forms import CustomResetPasswordForm, CustomResetPasswordConfirmForm, CustomUserCreationForm


def main(request):
    if request.user.is_authenticated:
        return redirect('account:dashboard')
    return render(request, 'base.html')


class CustomLoginView(LoginView):
    """
    Changes default authentication form to a custom one.
    Adds additional context - 'section'.
    """
    authentication_form = CustomLoginForm
    extra_context = {'section': 'login'}


class CustomResetPasswordView(PasswordResetView):
    form_class = CustomResetPasswordForm
    success_url = reverse_lazy('account:password_reset_done')


class CustomResetPasswordConfirmView(PasswordResetConfirmView):
    form_class = CustomResetPasswordConfirmForm
    success_url = reverse_lazy('account:password_reset_complete')


def register(request):
    if request.method == 'POST':
        user_form = CustomUserCreationForm(request.POST)
        if user_form.is_valid(): # Can't test this part, filled recaptcha is required
            new_user = user_form.save(commit=False)  # Create now, do not save in database  # pragma: no cover
            new_user.set_password(user_form.cleaned_data['password1'])                      # pragma: no cover
            new_user.save()                                                                 # pragma: no cover
            return render(request, 'account/register_done.html', {'new_user': new_user})    # pragma: no cover

    else:
        user_form = CustomUserCreationForm()
    return render(request, 'account/register.html', {'form': user_form, 'section': 'register'})

generator/account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">

    <!-- Required Bootstrap meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--Other meta-->
    <meta name="description" content="Test generator for teachers">
    <meta name="keywords" content="test generator, test, tests, generator">
    <meta http-equiv="X-Ua-Compatible" content="IE=edge">

    <!--MDB-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.9.0/mdb.min.css"
          integrity="sha512-MAFufI57w9mLGud8BKZDbAT57+wu4QWMJJ9Bj5UXFaW99rswsKCvXKRxWlHwdo0yT1Of6TvvWfMqE16ktRcxfA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"
    />

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet"/>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'account/images/favicon-32x32.png' %}"/>

    <!-- Highlight.js -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.3.1/styles/default.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.3.1/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>

    <!-- Mathjax plugin for CKEditor -->
    <script type="text/javascript" async
            src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML">
    </script>


    <!--Stylesheets-->
    <link rel="stylesheet" type="text/css" href="{% static 'account/css/main.css' %}">
    {% block additional_stylesheets %}{% endblock %}

    <title>{% block title %}Test Generator{% endblock %}</title>

    <script>
        function addClassesToTables() {
            let elements = document.getElementsByTagName('table');
            let elements2 = document.getElementsByTagName('tbody');
            for (let i = 0; i < elements.length; ++i) {
                elements[i].className = elements[i].className + " table table-bordered border-dark"
            }
            for (let i = 0; i < elements2.length; ++i) {
                elements2[i].className = elements2[i].className + " fw-bold"
            }
        }
    </script>
</head>

<body onload="addClassesToTables()">

<header class="sticky-top">

    <nav class="navbar navbar-dark bg-dark navbar-expand-md">

        <div class="container-fluid">

            <a class="navbar-brand ms-1" href="
                    {% if user.is_authenticated %}{% url 'account:dashboard' %}{% else %}{% url 'account:main' %}{% endif %}">
                <img class="d-inline-block mx-3 align-center" src="{% static 'account/images/favicon-64x64.png' %}"
                     alt="Logo" width="64" height="64">
                <span class="text-light ms-0">Test Generator</span>
            </a>

            <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#main-menu">
                <span class="navbar-toggler-icon"><i class="fas fa-bars"></i></span>
            </button>

            <div class="collapse navbar-collapse me-2" id="main-menu">

                {% if not user.is_authenticated %}
                    <div class="navbar-nav me-auto">
                        <!--Dummy div to make a div below stick to the right side of navbar-->
                    </div>
                    <div class="navbar-nav">
                        <a class="nav-link {% if section == 'login' %}active{% endif %}"
                           href="{% url 'account:login' %}">
                            Login
                        </a>
                        <a class="nav-link {% if section == 'register' %}active{% endif %}"
                           href="{% url 'account:register' %}">
                            Sign Up
                        </a>
                    </div>
                {% else %}
                    <button class="navbar-toggler me-2" type="button" data-bs-toggle="collapse"
                            data-bs-target="#main-menu">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="main-menu">

                    <div class="navbar-nav me-auto">

                        <div class="nav-item">
                            <a href="{% url 'account:dashboard' %}"
                               class="nav-link {% if section == 'dashboard' %}active{% endif %}">
                                Dashboard
                            </a>
                        </div>

                    </div>

                    {# NAVBAR RIGHT SIDE ------------------------------------------------------------------------------------------------ #}
                    <div class="navbar-nav">
                        <div class="nav-item">
                            <a href="{% url 'account:password_change' %}"
                               class="nav-link me-2 {% if section == 'profile' %}active{% endif %}">
                                Profile
                            </a>
                        </div>
                        <div class="nav-item">
                            <a href="{% url 'account:logout' %}" class="nav-link me-2">
                                Log Out
                            </a>
                        </div>
                    </div>
                    <div>
                {% endif %}

                </div>

                </div>

    </nav>
</header>

<main>
    {% block content %}
        <section class="min-vh-100 gradient-custom container-fluid pb-5">
            <div class="text-center pt-5">
                <h1 class="h1 text-light pt-5">
                    Test Generator
                </h1>
                <p class="text-light">
                    We will help you in creating and maintaining tests for your classes! <br>
                    If you are a teacher, we are here for you!
                </p>
            </div>
        </section>
    {% endblock %}
</main>

<script src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.9.0/mdb.min.js"
        integrity="sha512-NomYb5rMKF3A008ob4pKQ2U8/1j5U7tP1ScVtEKriqH9JmO4UiGYiDocerfvTxSFq7/2b+SSnSvGNBVhhwXNEw=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
<script>
    var csrftoken = Cookies.get('csrftoken');

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    $(document).ready(function () {
        {% block domready %}
        {% endblock %}
    });
</script>

</body>

</html>