generator/generator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('dashboard/', include('questions.urls', namespace='questions')),
    path('dashboard/', include('quiz.urls', namespace='quiz')),
    path('', include('account.urls', namespace='account')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

generator/questions/urls.py
from django.urls import path
from . import views

app_name = 'questions'
urlpatterns = [
    # Question and answers
    path('subject/<int:subject_id>/<slug:subject_slug>/<int:question_id>/', views.question, name='question'),
    path('subject/<int:subject_id>/<slug:subject_slug>/<int:question_id>/edit/',
         views.edit_question, name='question-edit'),
    path('subject/<int:subject_id>/<slug:subject_slug>/<int:question_id>/add-answer/',
         views.add_answer, name='question-add-answer'),
    path('subject/<int:subject_id>/<slug:subject_slug>/<int:question_id>/<int:answer_id>/edit-answer/',
         views.edit_answer, name='question-edit-answer'),
    path('subject/<int:subject_id>/<slug:subject_slug>/add-question/', views.create_question, name='question-create'),

    # Subject
    path('subject/<int:subject_id>/<slug:subject_slug>/edit/', views.edit_subject, name='subject-edit'),
    path('subject/<int:subject_id>/<slug:subject_slug>/people/add/', views.add_owner, name='subject-add-owner'),
    path('subject/<int:subject_id>/<slug:subject_slug>/people/', views.people, name='subject-people'),
    # List of questions in subject
    path('subject/<int:subject_id>/<slug:subject_slug>/tag/<slug:tag_slug>/', views.subject, name='subject-by-tag'),
    path('subject/<int:subject_id>/<slug:subject_slug>/', views.subject, name='subject'),
    path('subject/create/', views.create_subject, name='subject-create'),
]

generator/quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'
urlpatterns = [
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/create/', views.create_quiz, name='create-quiz'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/<int:quiz_id>/<slug:quiz_slug>/edit/',
         views.edit_quiz, name='edit-quiz'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/<int:quiz_id>/<slug:quiz_slug>/tag/<slug:tag_slug>',
         views.quiz, name='quiz-questions-by-tag'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/<int:quiz_id>/<slug:quiz_slug>/add-question/tag/<slug:tag_slug>/',
         views.add_question_to_quiz, name='add-question-to-quiz-by-tag'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/<int:quiz_id>/<slug:quiz_slug>/add-question/',
         views.add_question_to_quiz, name='add-question-to-quiz'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/<int:quiz_id>/<slug:quiz_slug>/',
         views.quiz, name='quiz'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/<int:quiz_id>/<slug:quiz_slug>/pdf/',
         views.quiz_pdf, name='quiz-pdf'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/tag/<slug:tag_slug>/', views.quizzes, name='quiz-by-tag'),
    path('subject/<int:subject_id>/<slug:subject_slug>/tests/', views.quizzes, name='quizzes'),
]

generator/quiz/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from questions.models import Question, Subject


class Quiz(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(blank=True)  # Generated automatically on creation
    description = models.CharField(max_length=250, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='quizzes')
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='quizzes')
    tags = TaggableManager(blank=True)

    __original_name = None

    def __init__(self, *args, **kwargs):
        super(Quiz, self).__init__(*args, **kwargs)
        self.__original_name = self.name

    def __str__(self):
        return f'ID: {self.id}, NAME: {self.name}'

    def save(self, *args, **kwargs):
        # Create slug only when object is being created or name has been updated
        if not self.id or self.name != self.__original_name:
            self.slug = slugify(self.name)
        super(Quiz, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('quiz:quiz', args=[self.subject.id, self.subject.slug, self.id, self.slug])


class QuizQuestion(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='quiz_questions')
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='question_quizzes')
    order = models.IntegerField()

    class Meta:
        # unique_together = ('quiz', 'order')
        required_db_features = {
            'supports_deferrable_unique_constraints'
        }
        constraints = [models.UniqueConstraint(
                fields=['quiz', 'question'],
                name='quiz_questions_unique',
                deferrable=models.Deferrable.DEFERRED,
            ),
            models.UniqueConstraint(
                fields=['quiz', 'question', 'order'],
                name='quiz_questions_order_unique',
                deferrable=models.Deferrable.DEFERRED,
            )
        ]

generator/quiz/forms.py
from django import forms
from taggit.forms import TagWidget
from .models import Quiz


class QuizCreationForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'

    class Meta:
        model = Quiz
        fields = ('name', 'description', 'tags')
        widgets = {
            'tags': TagWidget()
        }

generator/quiz/views.py
import os
import random
import re
import datetime

import weasyprint
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.search import TrigramSimilarity, SearchQuery, SearchVector, SearchRank
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db import transaction
from django.db.models.functions import Greatest
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from sympy import preview
from taggit.models import Tag

from generator.settings import MEDIA_ROOT, MEDIA_URL
from questions.forms import SearchForm, SearchTagForm
from questions.models import Answer
from questions.models import Subject, Question
from questions.utils import is_author_of_subject
from .forms import QuizCreationForm
from .models import Quiz, QuizQuestion
from .utils import is_author_of_quiz


@login_required
@require_http_methods(['GET', 'POST'])
def quizzes(request, subject_id, subject_slug, tag_slug=None):
    if request.method == 'POST':

        # Quiz deletion
        quiz_to_delete_id = request.POST.get('delete')
        if quiz_to_delete_id:
            try:
                quiz_to_delete_id = int(quiz_to_delete_id)
                # Check if user is an author of a quiz or an author of a subject - only those can delete a quiz
                if not is_author_of_quiz(request.user, quiz_to_delete_id) and \
                        not is_author_of_subject(request.user, subject_id):
                    raise Exception

                Quiz.objects.get(id=quiz_to_delete_id).delete()

            except Exception:
                return redirect('account:dashboard')

        # Quiz copy
        quiz_to_copy_id = request.POST.get('copy')
        if quiz_to_copy_id:
            try:
                quiz_to_copy_id = int(quiz_to_copy_id)
                # Check if user is an author of a quiz or an author of a subject - only those can delete a quiz
                if not is_author_of_quiz(request.user, quiz_to_copy_id) and \
                        not is_author_of_subject(request.user, subject_id):
                    raise Exception

                quiz = Quiz.objects.get(id=quiz_to_copy_id)

                new_quiz = Quiz.objects.create(name=quiz.name, description=quiz.description, author=quiz.author,
                                               subject=quiz.subject, tags=quiz.tags)

                for qq in quiz.quiz_questions.all():
                    QuizQuestion.objects.create(quiz=new_quiz, question=qq.question, order=qq.order)
                # quiz.id = None
                # quiz.save()

            except Exception:
                return redirect('account:dashboard')

    # GET/POST
    subject = get_object_or_404(Subject, id=subject_id)
    quizzes = subject.quizzes.all().order_by('-id')

    # Query search - questions and answers
    search_form = SearchForm()
    query = None
    if 'query' in request.GET:
        search_form = SearchForm(request.GET)
        if search_form.is_valid():
            query = search_form.cleaned_data['query']
            # Trigram search
            quizzes = quizzes.annotate(
                similarity=Greatest(TrigramSimilarity('name', query), TrigramSimilarity('description', query))
            ).filter(similarity__gt=0.1).order_by('-similarity')

    # Query search - tags
    tag_search_form = SearchTagForm()
    tag_query = None
    if 'tag_query' in request.GET:
        tag_search_form = SearchTagForm(request.GET)
        if tag_search_form.is_valid():
            tag_query = tag_search_form.cleaned_data['tag_query']
            # Trigram search
            quizzes = quizzes.annotate(
                similarity=TrigramSimilarity('tags__name', tag_query)
            ).filter(similarity__gt=0.1).order_by('id', '-similarity').distinct('id')

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        quizzes = quizzes.filter(tags__in=[tag])

    paginator = Paginator(quizzes, 12)
    page = request.GET.get('page')
    try:
        quizzes_page = paginator.page(page)
    except PageNotAnInteger:
        # If page value is not int - get first page
        quizzes_page = paginator.page(1)
    except EmptyPage:
        # If page value is bigger than the value of last page - get last page
        quizzes_page = paginator.page(paginator.num_pages)

    if is_author_of_subject(request.user, subject.id):
        authorial_quizzes = quizzes
    else:
        authorial_quizzes = request.user.quizzes.filter(subject_id=subject_id).all()
    return render(request, 'quiz/quizzes.html', {'quizzes': quizzes_page,
                                                 'authorial_quizzes': authorial_quizzes,
                                                 'subject': subject,
                                                 'tag': tag, 'query': query,
                                                 'search_form': search_form,
                                                 'tag_query': tag_query,
                                                 'tag_search_form': tag_search_form})


@login_required
@require_http_methods(['GET', 'POST'])
def create_quiz(request, subject_id, subject_slug):
    if request.method == 'POST':
        quiz_form = QuizCreationForm(data=request.POST)
        if quiz_form.is_valid():
            new_quiz = quiz_form.save(commit=False)
            new_quiz.author = request.user
            new_quiz.subject = get_object_or_404(Subject, id=subject_id)
            new_quiz.save()
            quiz_form.save_m2m()
            return redirect(reverse('quiz:quizzes', args=[subject_id, subject_slug]))
    else:
        quiz_form = QuizCreationForm()
    return render(request, 'quiz/quiz_create.html', {'quiz_form': quiz_form,
                                                     'subject': get_object_or_404(Subject, id=subject_id),
                                                     'section': 'create_quiz'})


@login_required
@require_http_methods(['GET', 'POST'])
def edit_quiz(request, subject_id, subject_slug, quiz_id, quiz_slug):
    # Check if user is an author of a quiz or an author of a subject
    if not is_author_of_quiz(request.user, quiz_id) or not is_author_of_subject(request.user, subject_id):
        # Just redirect - do not inform about illegal action
        return redirect(reverse('quiz:quizzes', args=[subject_id, subject_slug]))

    if request.method == 'POST':
        quiz_form = QuizCreationForm(data=request.POST)
        if quiz_form.is_valid():
            quiz = get_object_or_404(Quiz, id=quiz_id)
            quiz.name = quiz_form.cleaned_data['name']
            quiz.description = quiz_form.cleaned_data['description']

            # Remove tags
            for tag in quiz.tags.all():
                if tag.name not in re.split(', |,| ', quiz_form.data.get('tags')):
                    quiz.tags.remove(tag)

            # Add tags
            for tag in re.split(', |,| ', quiz_form.data.get('tags')):
                tag = tag.strip()
                if tag != '':
                    quiz.tags.add(tag)

            quiz.save()

            ret = request.POST.get('ret')
            if ret:
                return redirect(ret)

            return redirect(reverse('quiz:quizzes', args=[subject_id, subject_slug]))
    else:
        quiz = get_object_or_404(Quiz, id=quiz_id)
        subject = get_object_or_404(Subject, id=subject_id)
        quiz_form = QuizCreationForm(instance=quiz)

        ret = request.GET.get('ret')

        return render(request, 'quiz/quiz_create.html', {'quiz_form': quiz_form, 'section': 'edit_quiz',
                                                         'quiz': quiz, 'subject': subject, 'ret': ret})


@login_required
@require_http_methods(['GET', 'POST'])
def quiz(request, subject_id, subject_slug, quiz_id, quiz_slug, tag_slug=None):
    quiz = get_object_or_404(Quiz, id=quiz_id)

    # Remove question from
    if request.method == 'POST':

        # Quiz deletion
        quiz_to_delete_id = request.POST.get('delete_quiz')
        if quiz_to_delete_id:
            try:
                quiz_to_delete_id = int(quiz_to_delete_id)
                # Check if user is an author of a quiz or an author of a subject - only those can delete a quiz
                if not is_author_of_quiz(request.user, quiz_to_delete_id) and \
                        not is_author_of_subject(request.user, subject_id):
                    raise Exception

                Quiz.objects.get(id=quiz_to_delete_id).delete()

                return redirect(reverse('quiz:quizzes', args=[subject_id, subject_slug]))

            except Exception:
                return redirect(reverse('quiz:quizzes', args=[subject_id, subject_slug]))

        # Remove question from test
        question_id = request.POST.get('delete')
        if question_id:
            try:
                # Check if user is an author of a subject or an author of a quiz
                question_id = int(request.POST.get('delete'))
                if not is_author_of_quiz(request.user, quiz_id) and \
                        not is_author_of_subject(request.user, subject_id):
                    raise Exception

                QuizQuestion.objects.filter(quiz_id=quiz.id, question_id=question_id).delete()
            except Exception:
                pass

        if 'up' in request.POST:
            question_to_go_up = get_object_or_404(Question, id=int(request.POST.get('up')))
            quiz = get_object_or_404(Quiz, id=quiz_id)

            # Check rights to modify order
            if not is_author_of_quiz(request.user, quiz_id) and \
                    not is_author_of_subject(request.user, subject_id):

generator/quiz/templates/quiz/quiz.html
{% extends 'base.html' %}

{% block title %}
    {{ quiz.name }}
{% endblock %}

{% block content %}

    <section class="min-vh-100 gradient-custom container-fluid pb-5">
        <div class="d-flex justify-content-between position-relative top-0 start-0">
            <a class="btn btn-primary mt-2 ms-4" href="{% url 'quiz:quizzes' subject.id subject.slug %}">
                Return to Tests
            </a>
            <div>
                <a class="btn btn-success mt-2 {% if quiz.author != request.user and quiz.subject.author != request.user %}disabled{% endif %}"
                   href="{% url 'quiz:edit-quiz' subject.id subject.slug quiz.id quiz.slug %}?ret={{ request.build_absolute_uri }}">
                    Edit Test
                </a>
                <button type="button" data-mdb-toggle="modal"
                        data-mdb-target="#delete{{ quiz.id }}"
                        class="btn btn-danger mt-2 ms-2 {% if quiz.author != request.user and quiz.subject.author != request.user %}disabled{% endif %}">
                    Delete Test
                </button>
                <form method="post" class="d-inline">
                    {% csrf_token %}
                    <input type="hidden" name="randomize" value="yes">
                    <button type="submit"
                            class="btn btn-primary mt-2 ms-2 {% if quiz.author != request.user and quiz.subject.author != request.user %}disabled{% endif %}">
                        Randomize Question Order
                    </button>
                </form>
                <a class="btn btn-primary mt-2 ms-2"
                   href="{% url 'quiz:quiz-pdf' subject.id subject.slug quiz.id quiz.slug %}?answers=yes">
                    Print Test With Answers
                </a>
                <a class="btn btn-primary mt-2 ms-2"
                   href="{% url 'quiz:quiz-pdf' subject.id subject.slug quiz.id quiz.slug %}">
                    Print Test
                </a>
            </div>
        </div>

        <h1 class="text-light text-center pt-4">
            <a class="text-decoration-none text-light"
               href="{% url 'quiz:quiz' subject.id subject.slug quiz.id quiz.slug %}">
                {{ subject.name }} <br>
                {{ quiz.name }}
            </a>
        </h1>

        <div class="container mx-auto px-auto">

            {% if quiz.tags %}
                <div class="text-center">
                    {% for tag in quiz.tags.all %}
                        <a
                                href="{% url 'quiz:quiz-by-tag' subject.id subject.slug tag.slug %}"
                                class="badge badge-primary mx-1">{{ tag.name }}
                        </a>
                    {% endfor %}
                </div>
            {% endif %}

            {% if quiz.description %}
                <p class="text-light text-center mt-3">
                    {{ quiz.description }}
                </p>
            {% endif %}

            {% if quiz.author == request.user or quiz.subject.author == request.user %}
                <div class="row my-3 row-cols-1 row-cols-md-2 pb-3">
                    <div class="card col-md-12 bg-dark text-light my-3 py-2">
                        <div class="card-body">
                            <h5 class="card-title text-center">
                                Add Question to the Test
                            </h5>
                            <p class="card-text text-center">
                                <a href="{% url 'quiz:add-question-to-quiz' subject.id subject.slug quiz.id quiz.slug %}">
                                    <i class="fas fa-plus fa-5x mt-4"></i>
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            {% endif %}

            <div class="accordion" id="accordionPanelsStayOpen">
                {% if tag %}
                    <div class="d-flex justify-content-center mb-3">
                        <h2 class="h2 text-light">Test questions with tag: <span
                                class="text-danger">{{ tag.name }}</span>
                        </h2>
                    </div>
                {% endif %}

                <div class="d-flex justify-content-around mb-5">
                    <form method="get" class="w-25 text-center">

                        <div class="form-outline form-white mb-4">
                            {{ search_form.query.errors }}
                            {{ search_form.query }}
                            <label class="form-label" for="query">Search in questions and answers</label>
                        </div>

                        <button type="submit" class="btn-outline-warning btn-rounded">Search</button>
                    </form>

                    <form method="get" class="w-25 text-center">

                        <div class="form-outline form-white mb-4">
                            {{ tag_search_form.tag_query.errors }}
                            {{ tag_search_form.tag_query }}
                            <label class="form-label" for="tag_query">Search in tags</label>
                        </div>

                        <button type="submit" class="btn-outline-warning btn-rounded">Search</button>
                    </form>
                </div>

                {% if query %}
                    <div class="d-flex justify-content-center">
                        <h2 class="h2 text-light">Questions containing: <span
                                class="text-danger">{{ query }}</span>
                        </h2>
                    </div>
                {% endif %}

                {% if tag_query %}
                    <div class="d-flex justify-content-center">
                        <h2 class="h2 text-light">Questions with tags containing: <span
                                class="text-danger">{{ tag_query }}</span>
                        </h2>
                    </div>
                {% endif %}

                <div id="question-list">
                    {% include 'quiz/quiz_questions_ajax.html' %}
                </div>

            </div>
        </div>
        <div class="d-flex justify-content-center align-items-center mt-5">
            {% include 'quiz/pagination.html' with page=questions %}
        </div>

        <div class="position-fixed bottom-0 end-0 mb-3 me-3" style="z-index: 9999">
            <button type="button" class="btn btn-warning btn-floating btn-lg" id="scrollBtn" style="display: none">
                <i class="fas fa-arrow-up"></i>
            </button>
        </div>


        <div class="modal" tabindex="-1" role="dialog" id="delete{{ quiz.id }}">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Delete Test</h5>
                        <button type="button" class="btn-close" data-mdb-dismiss="modal"></button>
                    </div>
                    <div class="modal-body">
                        <p>Are you sure you want to delete {{ quiz.name }}?</p>
                    </div>
                    <div class="modal-footer">
                        <form method="post">
                            {% csrf_token %}
                            <input type="hidden" name="delete_quiz" value="{{ quiz.id }}">
                            <button type="submit" class="btn btn-danger">Yes, delete</button>
                        </form>
                        <button type="button" class="btn btn-success" data-mdb-dismiss="modal">
                            No, cancel
                        </button>
                    </div>
                </div>
            </div>
        </div>

    </section>


    <script>
        let scrollBtn = document.getElementById("scrollBtn");

        // When the user scrolls down 20px from the top of the document, show the button
        window.onscroll = function () {
            scrollFunction()
        };

        function scrollFunction() {
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                scrollBtn.style.display = "block";
            } else {
                scrollBtn.style.display = "none";
            }
        }

        scrollBtn.addEventListener("click", topFunction);

        // When the user clicks on the button, scroll to the top of the document
        function topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
        }
    </script>

{% endblock %}

generator/quiz/templates/quiz/quiz_questions_ajax.html
{% for question in questions %}

    <div class="accordion-item rounded mt-3">
        <nav class="navbar navbar-light bg-transparent">

            <div class="container-fluid d-flex justify-content-center mb-2">
                <div>
                    {% for tag in question.tags.all %}
                        <a
                                href="{% url 'quiz:quiz-questions-by-tag' question.subject.id question.subject.slug quiz.id quiz.slug tag.slug %}"
                                class="badge badge-primary mx-1">{{ tag.name }}
                        </a>
                    {% endfor %}
                </div>
            </div>

            <div class="container-fluid">
                <a class="btn btn-success {% if question.author != user %}disabled{% endif %}"
                   href="{% url 'questions:question' subject.id subject.slug question.id %}">
                    Edit
                </a>
                <div class="d-flex text-center">

                    <div class="ms-5 ps-5">
                        {% if forloop.first and forloop.first != forloop.last %}
                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="down" value="{{ question.id }}">
                                <button type="submit" class="btn btn-primary btn-floating btn-md">
                                    <i class="fas fa-arrow-down"></i>
                                </button>
                            </form>
                        {% elif forloop.last and forloop.first != forloop.last %}
                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="up" value="{{ question.id }}">
                                <button type="submit" class="btn btn-primary btn-floating btn-md">
                                    <i class="fas fa-arrow-up"></i>
                                </button>
                            </form>
                        {% elif not forloop.first and not forloop.last %}
                            <form method="post" class="me-1" style="float: left">
                                {% csrf_token %}
                                <input type="hidden" name="down" value="{{ question.id }}">
                                <button type="submit" class="btn btn-primary btn-floating btn-md">
                                    <i class="fas fa-arrow-down"></i>
                                </button>
                            </form>
                            <form method="post" class="ms-1" style="float:left;">
                                {% csrf_token %}
                                <input type="hidden" name="up" value="{{ question.id }}">
                                <button type="submit" class="btn btn-primary btn-floating btn-md">
                                    <i class="fas fa-arrow-up"></i>
                                </button>
                            </form>
                        {% endif %}
                    </div>

                </div>
                <button type="button" data-mdb-toggle="modal"
                        data-mdb-target="#delete{{ question.id }}"
                        class="btn btn-danger {% if quiz.author != user and subject.author != user %}disabled{% endif %}">
                    Remove from Test
                </button>
            </div>
        </nav>

        <h2 class="accordion-header" id="heading{{ question.id }}">
            <button class="accordion-button d-block collapsed" type="button" data-mdb-toggle="collapse"
                    data-mdb-target="#panelsStayOpen-collapse{{ question.id }}">
                {{ question.question|safe }}
            </button>
        </h2>
        <div id="panelsStayOpen-collapse{{ question.id }}" class="accordion-collapse collapse">
            <div class="accordion-body">
                <div class="d-flex justify-content-center border-bottom border-dark mb-2">
                    <h3 class="h3">Answers</h3>
                </div>

                {% for answer in question.answers.all %}
                    {% if answer.is_right %}
                        <div class="p-2 my-2" style="border: 3px green solid; border-radius: 15px">
                            {{ answer.answer|safe }}
                        </div>
                    {% else %}
                        <div class="p-2 my-2" style="border: 3px red solid; border-radius: 15px">
                            {{ answer.answer|safe }}
                        </div>
                    {% endif %}
                {% endfor %}

                <div class="d-flex justify-content-between border-top border-dark mt-2">
                    <div>
                        Created:
                        {{ question.created }}
                    </div>
                    <div>
                        Edited:
                        {{ question.edited }}
                    </div>
                    <div>
                        Used:
                        {% if question.last_use %}
                            {{ question.last_use }}
                        {% else %}
                            Never
                        {% endif %}
                    </div>
                </div>

            </div>
        </div>
    </div>

    {# Delete dialog #}
    <div class="modal" tabindex="-1" role="dialog" id="delete{{ question.id }}">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Remove Question from Test</h5>
                    <button type="button" class="btn-close" data-mdb-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to remove the question from the test?</p>
                </div>
                <div class="modal-footer">
                    <form method="post">
                        {% csrf_token %}
                        <input type="hidden" name="delete" value="{{ question.id }}">
                        <button type="submit" class="btn btn-danger">Yes, remove</button>
                    </form>
                    <button type="button" class="btn btn-success" data-mdb-dismiss="modal">
                        No, cancel
                    </button>
                </div>
            </div>
        </div>
    </div>

{% empty %}

    <div class="d-flex justify-content-center mt-5">
        <h1 class="h1 text-danger">No questions</h1>
    </div>

{% endfor %}